// This file is auto-generated by @hey-api/openapi-ts

export const $AvailableModels = {
    title: 'AvailableModels',
    enum: ['gpt-3.5-turbo'],
    type: 'string',
    description: 'An enumeration.'
} as const;

export const $ChatStreamRequest = {
    title: 'ChatStreamRequest',
    required: ['messages', 'model'],
    type: 'object',
    properties: {
        messages: {
            title: 'Messages',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Message'
            }
        },
        model: {
            '$ref': '#/components/schemas/AvailableModels'
        }
    }
} as const;

export const $HTTPValidationError = {
    title: 'HTTPValidationError',
    type: 'object',
    properties: {
        detail: {
            title: 'Detail',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ValidationError'
            }
        }
    }
} as const;

export const $Language = {
    title: 'Language',
    enum: ['en', 'es'],
    type: 'string',
    description: 'An enumeration.'
} as const;

export const $Message = {
    title: 'Message',
    required: ['role', 'content'],
    type: 'object',
    properties: {
        role: {
            '$ref': '#/components/schemas/Role'
        },
        content: {
            title: 'Content',
            type: 'string'
        }
    }
} as const;

export const $PingResponse = {
    title: 'PingResponse',
    required: ['message'],
    type: 'object',
    properties: {
        message: {
            title: 'Message',
            type: 'string'
        },
        environment: {
            title: 'Environment',
            type: 'string',
            default: 'jotta-dev'
        },
        prefix: {
            title: 'Prefix',
            type: 'string',
            default: 'local'
        }
    }
} as const;

export const $PosTag = {
    title: 'PosTag',
    enum: ['ADJ', 'ADP', 'PUNCT', 'ADV', 'AUX', 'SYM', 'INTJ', 'CCONJ', 'X', 'NOUN', 'DET', 'PROPN', 'NUM', 'VERB', 'PART', 'PRON', 'SCONJ'],
    type: 'string',
    description: `Universal POS tags.
See https://universaldependencies.org/ for more information.`
} as const;

export const $Role = {
    title: 'Role',
    enum: ['system', 'user', 'assistant'],
    type: 'string',
    description: 'An enumeration.'
} as const;

export const $SpacyProcessResponse = {
    title: 'SpacyProcessResponse',
    required: ['data'],
    type: 'object',
    properties: {
        data: {
            title: 'Data',
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SpacyToken'
            }
        }
    }
} as const;

export const $SpacyToken = {
    title: 'SpacyToken',
    required: ['text', 'pos', 'lemma', 'is_sent_start'],
    type: 'object',
    properties: {
        text: {
            title: 'Text',
            type: 'string'
        },
        pos: {
            '$ref': '#/components/schemas/PosTag'
        },
        lemma: {
            title: 'Lemma',
            type: 'string'
        },
        is_sent_start: {
            title: 'Is Sent Start',
            type: 'boolean'
        }
    }
} as const;

export const $ValidationError = {
    title: 'ValidationError',
    required: ['loc', 'msg', 'type'],
    type: 'object',
    properties: {
        loc: {
            title: 'Location',
            type: 'array',
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            }
        },
        msg: {
            title: 'Message',
            type: 'string'
        },
        type: {
            title: 'Error Type',
            type: 'string'
        }
    }
} as const;