// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class DefaultService {
    /**
     * Ping
     * @returns PingResponse Successful Response
     * @throws ApiError
     */
    public static pingGet(): CancelablePromise<$OpenApiTs['/']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
    /**
     * Process
     * @param data The data for the request.
     * @param data.text
     * @param data.language
     * @returns SpacyProcessResponse Successful Response
     * @throws ApiError
     */
    public static processProcessGet(data: $OpenApiTs['/process']['get']['req']): CancelablePromise<$OpenApiTs['/process']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/process',
            query: {
                text: data.text,
                language: data.language
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Chat Stream
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Stream plain text using utf8 charset.
     * @throws ApiError
     */
    public static chatStreamChatStreamPost(data: $OpenApiTs['/chat/stream']['post']['req']): CancelablePromise<$OpenApiTs['/chat/stream']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/chat/stream',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}