// This file is auto-generated by @hey-api/openapi-ts

/**
 * An enumeration.
 */
export type AvailableModels = 'gpt-3.5-turbo';

export type ChatStreamRequest = {
    messages: Array<Message>;
    model: AvailableModels;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * An enumeration.
 */
export type Language = 'en' | 'es';

export type Message = {
    role: Role;
    content: string;
};

export type PingResponse = {
    message: string;
    environment?: string;
    prefix?: string;
};

/**
 * Universal POS tags.
 * See https://universaldependencies.org/ for more information.
 */
export type PosTag = 'ADJ' | 'ADP' | 'PUNCT' | 'ADV' | 'AUX' | 'SYM' | 'INTJ' | 'CCONJ' | 'X' | 'NOUN' | 'DET' | 'PROPN' | 'NUM' | 'VERB' | 'PART' | 'PRON' | 'SCONJ';

/**
 * An enumeration.
 */
export type Role = 'system' | 'user' | 'assistant';

export type SpacyProcessResponse = {
    data: Array<SpacyToken>;
};

export type SpacyToken = {
    text: string;
    pos: PosTag;
    lemma: string;
    is_sent_start: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: PingResponse;
            };
        };
    };
    '/process': {
        post: {
            req: {
                language: Language;
                text: string;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: SpacyProcessResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/chat/stream': {
        post: {
            req: {
                requestBody: ChatStreamRequest;
            };
            res: {
                /**
                 * Stream plain text using utf8 charset.
                 */
                200: any;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};