// Generated by ts-to-zod
import { z } from "zod";

export const availableModelsSchema = z.literal("gpt-3.5-turbo");

export const validationErrorSchema = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
});

export const languageSchema = z.union([z.literal("en"), z.literal("es")]);

export const roleSchema = z.union([
  z.literal("system"),
  z.literal("user"),
  z.literal("assistant"),
]);

export const pingResponseSchema = z.object({
  message: z.string(),
  environment: z.string().optional(),
  prefix: z.string().optional(),
});

export const posTagSchema = z.union([
  z.literal("ADJ"),
  z.literal("ADP"),
  z.literal("PUNCT"),
  z.literal("ADV"),
  z.literal("AUX"),
  z.literal("SYM"),
  z.literal("INTJ"),
  z.literal("CCONJ"),
  z.literal("X"),
  z.literal("NOUN"),
  z.literal("DET"),
  z.literal("PROPN"),
  z.literal("NUM"),
  z.literal("VERB"),
  z.literal("PART"),
  z.literal("PRON"),
  z.literal("SCONJ"),
]);

export const spacyTokenSchema = z.object({
  text: z.string(),
  pos: posTagSchema,
  lemma: z.string(),
  is_sent_start: z.boolean(),
});

export const messageSchema = z.object({
  role: roleSchema,
  content: z.string(),
});

export const hTTPValidationErrorSchema = z.object({
  detail: z.array(validationErrorSchema).optional(),
});

export const spacyProcessResponseSchema = z.object({
  data: z.array(spacyTokenSchema),
});

export const chatStreamRequestSchema = z.object({
  messages: z.array(messageSchema),
  model: availableModelsSchema,
});

export const openApiTsSchema = z.object({
  "/": z.object({
    get: z.object({
      res: z.object({
        200: pingResponseSchema,
      }),
    }),
  }),
  "/process": z.object({
    get: z.object({
      req: z.object({
        language: languageSchema,
        text: z.string(),
      }),
      res: z.object({
        200: spacyProcessResponseSchema,
        422: hTTPValidationErrorSchema,
      }),
    }),
  }),
  "/chat/stream": z.object({
    post: z.object({
      req: z.object({
        requestBody: chatStreamRequestSchema,
      }),
      res: z.object({
        200: z.any(),
        422: hTTPValidationErrorSchema,
      }),
    }),
  }),
});
