name: Preview Production Build

on: [pull_request]

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  MODAL_ENVIRONMENT: ${{ secrets.MODAL_ENVIRONMENT_PROD }}
  MODAL_APP_PREFIX: ${{ secrets.MODAL_APP_PREFIX_PROD }}

jobs:
  preview-production-build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Setup .env
        run: |
          touch .env
          echo MODAL_APP_PREFIX=${{ env.MODAL_APP_PREFIX }} >> .env
          echo MODAL_ENVIRONMENT=${{ env.MODAL_ENVIRONMENT }} >> .env

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
